import { loadDb, saveDb } from "./storage";

export function seedIfEmpty() {
  if (typeof window === "undefined") return;

  const db = loadDb();
  const hasAny = (db.moc?.length ?? 0) + (db.ptw?.length ?? 0) > 0;
  if (hasAny) return;

  const now = new Date().toISOString();

  db.moc = [
    {
      id: "MOC-0001",
      status: "SUBMITTED",
      title: "Boiler Room Equipment Upgrade",
      area: "Building A",
      exactLocation: "Boiler Room, 2nd Floor",
      description: "Replace outdated boiler control systems with modern digital controls for improved efficiency and safety monitoring.",
      reasonForChange: "Existing equipment is obsolete and parts are no longer available. Upgrading will improve safety and energy efficiency.",
      riskSummary: "Hot work required. Potential for steam release. All safety protocols will be followed with proper isolation procedures.",
      startDate: "2024-02-15",
      endDate: "2024-03-15",
      contractorCompany: "ABC Contractors",
      requiresStakeholderApproval: false,
      createdAt: now,
      createdByRole: "HSE Manager",
      createdBy: "John Smith",
    },
    {
      id: "MOC-0002",
      status: "STAKEHOLDER_SIGNED",
      title: "New HVAC System Installation",
      area: "Building B",
      exactLocation: "Production Area, West Wing",
      description: "Install new HVAC system to improve air quality and temperature control in production area.",
      reasonForChange: "Current system is inadequate for production requirements and causing quality issues.",
      riskSummary: "Work at height required. Electrical work involved. Full PPE and safety measures in place.",
      startDate: "2024-02-20",
      endDate: "2024-04-20",
      contractorCompany: "ABC Contractors",
      requiresStakeholderApproval: true,
      stakeholderName: "Jane Doe",
      stakeholderEmail: "jane.doe@unilever.com",
      stakeholderSignature: "Jane Doe",
      stakeholderSignedAt: now,
      createdAt: now,
      createdByRole: "Stakeholder",
      createdBy: "Jane Doe",
    },
    {
      id: "MOC-0003",
      status: "CONTRACTOR_SUBMITTED",
      title: "Electrical Panel Replacement",
      area: "Building C",
      exactLocation: "Main Electrical Room",
      description: "Replace aging electrical panels with modern circuit breakers and safety features.",
      reasonForChange: "Panels are 20+ years old and pose safety risk. Modern panels will provide better protection.",
      riskSummary: "Electrical isolation required. Hot work involved. Trained electricians only.",
      startDate: "2024-03-01",
      endDate: "2024-03-31",
      contractorCompany: "ABC Contractors",
      requiresStakeholderApproval: false,
      contractorGate: {
        acknowledged: true,
        acknowledgedBy: "ABC Contractors",
        acknowledgedAt: new Date(new Date().getTime() - 24 * 60 * 60 * 1000).toISOString(),
        signature: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
        supervisorName: "Mike Johnson",
        supervisorPhone: "+1 555-0123",
        supervisorEmail: "mike.johnson@abc.com",
        supervisorIdPassport: "ID123456",
        documents: {
          companyCertificates: "ABC_Certificates_2024.pdf",
          methodStatement: "Electrical_Panel_MOS.pdf",
          riskAssessment: "Panel_Replacement_RA.pdf",
          projectPlan: "Electrical_Project_Schedule.pdf",
        },
        submittedAt: new Date(new Date().getTime() - 24 * 60 * 60 * 1000).toISOString(),
      },
      createdAt: now,
      createdByRole: "HSE Manager",
      createdBy: "John Smith",
    },
    {
      id: "MOC-0004",
      status: "FACILITIES_CHANGES_REQUESTED",
      title: "Cooling Tower Maintenance",
      area: "Building D",
      exactLocation: "Rooftop Cooling System",
      description: "Perform comprehensive cooling tower maintenance including cleaning, inspection, and component replacement.",
      reasonForChange: "Scheduled maintenance to prevent system failure and ensure optimal cooling efficiency.",
      riskSummary: "Work at height. Chemical handling. Lockout/tagout procedures required.",
      startDate: "2024-03-05",
      endDate: "2024-03-12",
      contractorCompany: "ABC Contractors",
      requiresStakeholderApproval: false,
      contractorGate: {
        acknowledged: true,
        acknowledgedBy: "ABC Contractors",
        acknowledgedAt: new Date(new Date().getTime() - 48 * 60 * 60 * 1000).toISOString(),
        signature: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
        supervisorName: "Mike Johnson",
        supervisorPhone: "+1 555-0123",
        supervisorEmail: "mike.johnson@abc.com",
        supervisorIdPassport: "ID123456",
        documents: {
          companyCertificates: "ABC_Certificates_2024.pdf",
          methodStatement: "Cooling_Tower_MOS.pdf",
          riskAssessment: "Cooling_RA.pdf",
          projectPlan: "Maintenance_Schedule.pdf",
        },
        submittedAt: new Date(new Date().getTime() - 48 * 60 * 60 * 1000).toISOString(),
      },
      facilitiesApproval: {
        status: "CHANGES_REQUESTED",
        signedAt: new Date(new Date().getTime() - 24 * 60 * 60 * 1000).toISOString(),
        signedBy: "Facilities Manager",
        changesRequested: "Please provide updated risk assessment with specific controls for chemical handling and additional fall protection measures.",
      },
      createdAt: new Date(new Date().getTime() - 72 * 60 * 60 * 1000).toISOString(),
      createdByRole: "HSE Manager",
      createdBy: "John Smith",
    },
    {
      id: "MOC-0005",
      status: "FACILITIES_APPROVED",
      title: "Production Line Modification",
      area: "Building E",
      exactLocation: "Production Floor, Line 3",
      description: "Modify production line layout to improve workflow efficiency and reduce bottlenecks.",
      reasonForChange: "Current layout causes delays and impacts production targets. Optimization required.",
      riskSummary: "Equipment movement. Electrical disconnection. Confined space entry possible.",
      startDate: "2024-03-10",
      endDate: "2024-04-15",
      contractorCompany: "XYZ Engineering",
      requiresStakeholderApproval: true,
      stakeholderName: "Production Manager",
      stakeholderEmail: "prod.manager@unilever.com",
      contractorGate: {
        acknowledged: true,
        acknowledgedBy: "XYZ Engineering",
        acknowledgedAt: new Date(new Date().getTime() - 72 * 60 * 60 * 1000).toISOString(),
        signature: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
        supervisorName: "Sarah Williams",
        supervisorPhone: "+1 555-0456",
        supervisorEmail: "sarah.w@xyz.com",
        supervisorIdPassport: "ID789012",
        documents: {
          companyCertificates: "XYZ_Certificates_2024.pdf",
          methodStatement: "Line_Modification_MOS.pdf",
          riskAssessment: "Production_Line_RA.pdf",
          projectPlan: "Line_Modification_Schedule.pdf",
        },
        submittedAt: new Date(new Date().getTime() - 72 * 60 * 60 * 1000).toISOString(),
      },
      facilitiesApproval: {
        status: "APPROVED",
        signature: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
        signedAt: new Date(new Date().getTime() - 48 * 60 * 60 * 1000).toISOString(),
        signedBy: "Facilities Manager",
      },
      createdAt: new Date(new Date().getTime() - 96 * 60 * 60 * 1000).toISOString(),
      createdByRole: "HSE Manager",
      createdBy: "John Smith",
    },
    {
      id: "MOC-0006",
      status: "FACILITIES_APPROVED",
      title: "Steam Line Upgrade",
      area: "Building F",
      exactLocation: "Utility Corridor",
      description: "Replace aging steam distribution lines with new insulated piping system.",
      reasonForChange: "Current pipes show signs of corrosion and have reduced efficiency. Safety concern.",
      riskSummary: "Hot work. Steam system isolation. Asbestos survey completed (none found).",
      startDate: "2024-03-20",
      endDate: "2024-05-30",
      contractorCompany: "ABC Contractors",
      requiresStakeholderApproval: false,
      contractorGate: {
        acknowledged: true,
        acknowledgedBy: "ABC Contractors",
        acknowledgedAt: new Date(new Date().getTime() - 96 * 60 * 60 * 1000).toISOString(),
        signature: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
        supervisorName: "Mike Johnson",
        supervisorPhone: "+1 555-0123",
        supervisorEmail: "mike.johnson@abc.com",
        supervisorIdPassport: "ID123456",
        documents: {
          companyCertificates: "ABC_Certificates_2024.pdf",
          methodStatement: "Steam_Line_MOS.pdf",
          riskAssessment: "Steam_Upgrade_RA.pdf",
          projectPlan: "Steam_Project_Schedule.pdf",
        },
        submittedAt: new Date(new Date().getTime() - 96 * 60 * 60 * 1000).toISOString(),
      },
      facilitiesApproval: {
        status: "APPROVED",
        signature: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
        signedAt: new Date(new Date().getTime() - 72 * 60 * 60 * 1000).toISOString(),
        signedBy: "Facilities Manager",
      },
      createdAt: new Date(new Date().getTime() - 120 * 60 * 60 * 1000).toISOString(),
      createdByRole: "HSE Manager",
      createdBy: "John Smith",
    },
    {
      id: "MOC-0007",
      status: "STAKEHOLDER_APPROVED",
      title: "Warehouse Racking System",
      area: "Building G",
      exactLocation: "Warehouse Storage Area",
      description: "Install new high-bay racking system to increase storage capacity and improve inventory management.",
      reasonForChange: "Current storage at capacity. New system provides 40% more storage with better accessibility.",
      riskSummary: "Work at height. Forklift operations. Heavy lifting. Full site safety induction required.",
      startDate: "2024-04-01",
      endDate: "2024-06-30",
      contractorCompany: "Storage Solutions Ltd",
      requiresStakeholderApproval: true,
      stakeholderName: "Logistics Director",
      stakeholderEmail: "logistics@unilever.com",
      contractorGate: {
        acknowledged: true,
        acknowledgedBy: "Storage Solutions Ltd",
        acknowledgedAt: new Date(new Date().getTime() - 144 * 60 * 60 * 1000).toISOString(),
        signature: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
        supervisorName: "David Chen",
        supervisorPhone: "+1 555-0789",
        supervisorEmail: "david.c@storage.com",
        supervisorIdPassport: "ID345678",
        documents: {
          companyCertificates: "Storage_Certificates_2024.pdf",
          methodStatement: "Racking_Installation_MOS.pdf",
          riskAssessment: "Racking_System_RA.pdf",
          projectPlan: "Warehouse_Project_Schedule.pdf",
        },
        submittedAt: new Date(new Date().getTime() - 144 * 60 * 60 * 1000).toISOString(),
      },
      facilitiesApproval: {
        status: "APPROVED",
        signature: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
        signedAt: new Date(new Date().getTime() - 120 * 60 * 60 * 1000).toISOString(),
        signedBy: "Facilities Manager",
      },
      stakeholderApproval: {
        signature: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
        signedAt: new Date(new Date().getTime() - 96 * 60 * 60 * 1000).toISOString(),
        signedBy: "Logistics Director",
      },
      createdAt: new Date(new Date().getTime() - 168 * 60 * 60 * 1000).toISOString(),
      createdByRole: "HSE Manager",
      createdBy: "John Smith",
    },
    {
      id: "MOC-0008",
      status: "APPROVED",
      title: "Emergency Exit Installation",
      area: "Building H",
      exactLocation: "West Wing, All Floors",
      description: "Install additional emergency exits to comply with updated fire safety regulations.",
      reasonForChange: "Fire safety audit identified need for additional egress routes. Regulatory compliance required.",
      riskSummary: "Structural work. Hot work. Noise and dust control. After-hours work preferred.",
      startDate: "2024-02-01",
      endDate: "2024-02-28",
      contractorCompany: "BuildSafe Contractors",
      requiresStakeholderApproval: false,
      contractorGate: {
        acknowledged: true,
        acknowledgedBy: "BuildSafe Contractors",
        acknowledgedAt: new Date(new Date().getTime() - 240 * 60 * 60 * 1000).toISOString(),
        signature: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
        supervisorName: "Robert Taylor",
        supervisorPhone: "+1 555-0321",
        supervisorEmail: "robert.t@buildsafe.com",
        supervisorIdPassport: "ID901234",
        documents: {
          companyCertificates: "BuildSafe_Certificates_2024.pdf",
          methodStatement: "Emergency_Exit_MOS.pdf",
          riskAssessment: "Exit_Installation_RA.pdf",
          projectPlan: "Exit_Project_Schedule.pdf",
        },
        submittedAt: new Date(new Date().getTime() - 240 * 60 * 60 * 1000).toISOString(),
      },
      facilitiesApproval: {
        status: "APPROVED",
        signature: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
        signedAt: new Date(new Date().getTime() - 216 * 60 * 60 * 1000).toISOString(),
        signedBy: "Facilities Manager",
      },
      hseApproval: {
        signature: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
        signedAt: new Date(new Date().getTime() - 192 * 60 * 60 * 1000).toISOString(),
        signedBy: "John Smith",
      },
      createdAt: new Date(new Date().getTime() - 264 * 60 * 60 * 1000).toISOString(),
      createdByRole: "HSE Manager",
      createdBy: "John Smith",
    },
  ];

  db.ptw = [
    {
      id: "PTW-0101",
      status: "Pending Final Review",
      title: "Hot work permit - Welding",
      location: "Plant A",
      createdAt: now,
      createdByRole: "Contractor",
      step: "Final Authority",
    },
  ];

  saveDb(db);
}
